id = "docker-compose"
name = "Docker Compose"
version = "0.3.1"
schema_version = 1
authors = ["eth0net <eth0net@pm.me>"]
description = "Syntax highlighting for Docker Compose files"
repository = "https://github.com/eth0net/zed-docker-compose"

[language_servers.docker-compose]
name = "Docker Compose"
language = "Docker Compose"

[grammars.docker-compose]
repository = "https://github.com/zed-industries/tree-sitter-yaml"
commit = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"
